#!/usr/bin/env bash
# Bash script that will display information about subdomains

func () {
    if [ -n "$2" ]
    then
        subdomain="$2"
        if [ "$subdomain" == "www" ]; then
            subdomain="#student"
        fi
        dig "$2.$1" | grep -A1 'ANSWER SECTION:' | paste - - | awk -v sd="$subdomain" '{print "The subdomain " sd " is a " $7 " record and points to " $8}'
    else
        dig "www.$1" | grep -A1 'ANSWER SECTION:' | paste - - | awk '{print "The subdomain #student is a " $7 " record and points to " $8}'
        dig "lb-01.$1" | grep -A1 'ANSWER SECTION:' | paste - - | awk '{print "The subdomain #student.lb-01 is a " $7 " record and points to " $8}'
        dig "web-01.$1" | grep -A1 'ANSWER SECTION:' | paste - - | awk '{print "The subdomain #student.web-01 is a " $7 " record and points to " $8}'
        dig "web-02.$1" | grep -A1 'ANSWER SECTION:' | paste - - | awk '{print "The subdomain #student.web-02 is a " $7 " record and points to " $8}'
    fi
}

func "$1" "$2"
