#!/usr/bin/env bash
# script that transfers a file from our client to a server.

if [ $# -lt 3 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  if [ $# -lt 4 ]; then
    echo "Error: Missing SSH Key. Please provide all 4 parameters."
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
  fi
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
