#!/usr/bin/env bash
# Configure your Nginx server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
sudo sed -i '/error_page 404/a \\t\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default
sudo sed -i '/location \/ {/a \\t\trewrite ^/redirect_me http://example.com/ permanent;' /etc/nginx/sites-available/default
sudo systemctl restart nginx
