#!/usr/bin/env bash
# This script pings the given IP address 5 times. The IP address must be provided as a parameter.

if [ $# -eq 0 ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c 5 "$1"
fi
