#!/usr/bin/env bash
# This script pings the given IP address 5 times. The IP address must be provided as a parameter.

if [ "$#" -lt "1" ]
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping "$1" -c 5
fi
