#!/usr/bin/env bash
#a Bash script that configuresrver
if [ -x "$(command -v nginx)" ]; the
  sed -i -e 's/listen [::]:80 default_server;/listen 80 default_server;/' /etc/nginx/sites-enabled/default
  service nginx restart
  echo 'Nginx configured to listen on port 80 of all active IPv4 IPs.'
else
  echo 'Error: Nginx is not installed.' >&2
  exit 1
fi
