#!/usr/bin/env bash
if ! command -v ufw &> /dev/null; then
    sudo apt-get install ufw
fi
sudo sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
sudo ufw --force reset
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
sudo ufw status verbose
