#!/usr/bin/env bash
# Configures the web server to run Nginx as the 'nginx' user on port 8080.
pkill apache2
chmod 644 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
